# Generated by Django 4.2.6 on 2023-11-02 20:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_alter_task_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[
                    ("urgent", "🔴 Urgent!!! 🔴"),
                    ("high", "🟠 High priority! 🟠"),
                    ("medium", "🟡 Medium priority. 🟡"),
                    ("low", "🟢 Low priority. 🟢"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
